theme = "gohugo-theme-ananke"
baseURL = "https://dotdoes.travel"
languageCode = "en-us"
title="DotDoes.Travel"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu ="main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/notthepoint"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-black"
  featured_image = "/images/pattern.svg"
  recent_posts_number = 2
  cover_dimming_class = "bg-clear"
